export type CategoryOnboarding = {
  name: string
  icon: string
  group: string
  color: string
}

export const onboardingCategories = [
  {
    name: "Combustível",
    icon: "⛽",
    group: "Carro & Transporte",
    color: "#34D399",
  },
  {
    name: "Estacionamento",
    icon: "🅿️",
    group: "Carro & Transporte",
    color: "#34D399",
  },
  {
    name: "Mecânica",
    icon: "🔧",
    group: "Carro & Transporte",
    color: "#34D399",
  },
  {
    name: "Multas",
    icon: "🚧",
    group: "Carro & Transporte",
    color: "#34D399",
  },
  {
    name: "Seguro",
    icon: "🛡️",
    group: "Carro & Transporte",
    color: "#34D399",
  },
  {
    name: "Aluguel",
    icon: "🏠",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Água",
    icon: "💧",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Condomínio",
    icon: "🏢",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Energia",
    icon: "🔥",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Manutenção",
    icon: "🔧",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Telefone",
    icon: "☎️",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "TV a cabo",
    icon: "📺",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Internet",
    icon: "📶",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Limpeza",
    icon: "🧹",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Segurança",
    icon: "🛡️",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Serviços",
    icon: "🔧",
    group: "Casa & Jardim",
    color: "#ff75c3",
  },
  {
    name: "Alimentação",
    icon: "🍽️",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Bebidas",
    icon: "🍺",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Mercado",
    icon: "🛒",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Restaurantes",
    icon: "🍽️",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Colégio",
    icon: "🏫",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Creche",
    icon: "👶",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Faculdade",
    icon: "🏫",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Livro escolar",
    icon: "📚",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Material escolar",
    icon: "🎒",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Transporte escolar",
    icon: "🚌",
    group: "Comida & Bebida",
    color: "#ffa647",
  },
  {
    name: "Cinema",
    icon: "🎬",
    group: "Entretenimento",
    color: "#cd93ff",
  },
  {
    name: "Jogos",
    icon: "🎮",
    group: "Entretenimento",
    color: "#cd93ff",
  },
  {
    name: "Livros",
    icon: "📚",
    group: "Entretenimento",
    color: "#cd93ff",
  },
  {
    name: "Música",
    icon: "🎵",
    group: "Entretenimento",
    color: "#cd93ff",
  },
  {
    name: "Revistas",
    icon: "📰",
    group: "Entretenimento",
    color: "#cd93ff",
  },
  {
    name: "Teatro",
    icon: "🎭",
    group: "Entretenimento",
    color: "#cd93ff",
  },
  {
    name: "Viagens",
    icon: "✈️",
    group: "Entretenimento",
    color: "#cd93ff",
  },
  {
    name: "Animais de estimação",
    icon: "🐾",
    group: "Família & Pets",
    color: "#f87171",
  },
  {
    name: "Babá",
    icon: "👶",
    group: "Família & Pets",
    color: "#f87171",
  },
  {
    name: "Brinquedos",
    icon: "🧸",
    group: "Família & Pets",
    color: "#f87171",
  },
  {
    name: "Cuidados com crianças",
    icon: "👶",
    group: "Família & Pets",
    color: "#f87171",
  },
  {
    name: "Despesas médicas",
    icon: "💉",
    group: "Família & Pets",
    color: "#f87171",
  },
  {
    name: "Roupas",
    icon: "👕",
    group: "Família & Pets",
    color: "#f87171",
  },
  {
    name: "Empréstimos",
    icon: "💳",
    group: "Finanças",
    color: "#FBBF24",
  },
  {
    name: "Financiamentos",
    icon: "🔑",
    group: "Finanças",
    color: "#FBBF24",
  },
  {
    name: "Impostos",
    icon: "📝",
    group: "Finanças",
    color: "#FBBF24",
  },
  {
    name: "Juros",
    icon: "🔢",
    group: "Finanças",
    color: "#FBBF24",
  },
  {
    name: "Seguros",
    icon: "🛡️",
    group: "Finanças",
    color: "#FBBF24",
  },
  {
    name: "Tarifas",
    icon: "💳",
    group: "Finanças",
    color: "#FBBF24",
  },

  {
    name: "Cuidados médicos",
    icon: "💊",
    group: "Saúde & Fitness",
    color: "#cd93ff",
  },
  {
    name: "Fitness",
    icon: "🏋️‍♂️",
    group: "Saúde & Fitness",
    color: "#cd93ff",
  },
  {
    name: "Medicamentos",
    icon: "💊",
    group: "Saúde & Fitness",
    color: "#cd93ff",
  },
  {
    name: "Nutrição",
    icon: "🍎",
    group: "Saúde & Fitness",
    color: "#cd93ff",
  },
]
